version: "3"
services:
  doh-proxy:
    image: jqtype/doh-proxy
    container_name: doh-proxy
    build:
      context: ./
      # args:
      #   - GIT_USER=${GIT_USER}
      #   - GIT_TOKEN=${GIT_TOKEN}
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000/udp
      - 3000:3000/tcp
    volumes:
      - ./.env:/opt/doh-proxy/etc/.env

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   command: dnscrypt-server --interval 30
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
